# -*- coding: utf-8 -*-
"""Trader_Performance_vs_Market_Sentiment_Primetrade.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDcqoi1KwthtevfuK_YvUsy6pG5rVrmb
"""

# Imported Required Libraries


import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from IPython.display import Markdown, display

# Plot Style
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (10, 5)

## Part A – Data Preparation
#Load Both CSV Files

sentiment = pd.read_csv("/content/fear_greed_index.csv")
trades = pd.read_csv("/content/historical_data.csv")

print(sentiment.head())
print(trades.head())

print("Sentiment Shape:", sentiment.shape)
print("Trades Shape:", trades.shape)

print(sentiment.columns)
print(trades.columns)

print(sentiment.isnull().sum())
print(trades.isnull().sum())
trades.fillna(0, inplace=True)

print("Sentiment Duplicates:", sentiment.duplicated().sum())
print("Trades Duplicates:", trades.duplicated().sum())

sentiment['date'] = pd.to_datetime(sentiment['date'])

# Convert timestamp safely
trades['Timestamp IST'] = pd.to_datetime(
    trades['Timestamp IST'],
    format='%d-%m-%Y %H:%M',
    errors='coerce'
)

# Remove invalid rows
trades = trades.dropna(subset=['Timestamp IST'])

# Create Date column
trades['Date'] = trades['Timestamp IST'].dt.date
trades['Date'] = pd.to_datetime(trades['Date'])

# Sentiment date convert
sentiment['date'] = pd.to_datetime(sentiment['date'])

# Rename
sentiment.rename(columns={'date':'Date'}, inplace=True)

# Merge
df = pd.merge(trades, sentiment, on='Date', how='left')

print(df.shape)
print(df.head())

#Bad Rows Found
print(trades['Timestamp IST'].isnull().sum())

print(df.isnull().sum())

df.columns = df.columns.str.strip()
print(df.columns)

#Win Rate
df['Win'] = (df['Closed PnL'] > 0).astype(int)

win_rate = df.groupby('Account')['Win'].mean() * 100
print(win_rate.head())

#Average Trade Size
avg_size = df.groupby('Account')['Size USD'].mean()
print(avg_size.head())

#Trades Per Day
trades_per_day = df.groupby('Date').size().reset_index(name='Trade Count')
print(trades_per_day.head())

#Long / Short Ratio
print(df['Side'].value_counts(normalize=True) * 100)

# Risk Exposure using Size USD
#The dataset did not contain leverage values. Therefore, Size USD was used as a proxy for trader risk appetite / exposure.

print(df['Size USD'].describe())

print(df['Size USD'].value_counts().head(10))

sns.histplot(df['Size USD'], bins=30, kde=True)
plt.title("Trade Size USD Distribution")
plt.show()

#Fear vs Greed PnL Comparison
sns.boxplot(data=df, x='classification', y='Closed PnL')
plt.title("PnL Distribution: Fear vs Greed")
plt.show()

#Top 10 Traders by Total PnL

import matplotlib.pyplot as plt
import seaborn as sns

# Clean style
sns.set_style("whitegrid")

# Create short account labels
df['Short_Account'] = df['Account'].astype(str).str[:6] + "..." + df['Account'].astype(str).str[-4:]

# Aggregate total pnl by trader
top10 = (
    df.groupby(['Account', 'Short_Account'])['Closed PnL']
    .sum()
    .reset_index()
    .sort_values(by='Closed PnL', ascending=False)
    .head(10)
    .sort_values(by='Closed PnL', ascending=True)
)

# Plot
plt.figure(figsize=(12,7))

bars = plt.barh(top10['Short_Account'], top10['Closed PnL'])

# Add value labels
for bar in bars:
    width = bar.get_width()
    plt.text(
        width,
        bar.get_y() + bar.get_height()/2,
        f'{width:,.0f}',
        va='center',
        ha='left',
        fontsize=10
    )

# Titles and labels
plt.title("Top 10 Traders by Total Closed PnL", fontsize=16, weight='bold')
plt.xlabel("Total Closed PnL")
plt.ylabel("Trader Account")

plt.tight_layout()
plt.show()

# PART B — ANALYSIS

# Performance by Sentiment

print("Performance Summary by Sentiment")
performance = df.groupby('classification')['Closed PnL'].agg(
    ['mean', 'median', 'sum', 'count']
)
print(performance)

# Win Rate by Sentiment
print("\nWin Rate by Sentiment (%)")
win_sentiment = df.groupby('classification')['Win'].mean() * 100
print(win_sentiment)

# Drawdown Proxy (Average Loss on Losing Trades)
print("\nDrawdown Proxy (Avg Loss)")
drawdown = df[df['Closed PnL'] < 0].groupby('classification')['Closed PnL'].mean()
print(drawdown)

# Chart: PnL Distribution
plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='classification', y='Closed PnL')
plt.title("PnL Distribution: Fear vs Greed")
plt.xlabel("Sentiment")
plt.ylabel("Closed PnL")
plt.show()

# Trader Behavior by Sentiment

# Trade Frequency
print("\nTrade Frequency by Sentiment")
trade_freq = df.groupby('classification').size()
print(trade_freq)

trade_freq.plot(kind='bar', figsize=(8,5))
plt.title("Trade Count by Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Number of Trades")
plt.show()

# Long / Short Bias
print("\nLong / Short Bias by Sentiment (%)")
bias = pd.crosstab(df['classification'], df['Side'], normalize='index') * 100
print(bias)

bias.plot(kind='bar', stacked=True, figsize=(8,5))
plt.title("Long / Short Bias by Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Percentage")
plt.show()

# Position Size / Risk Appetite
print("\nAverage Position Size (Size USD)")
size_behavior = df.groupby('classification')['Size USD'].mean()
print(size_behavior)

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='classification', y='Size USD')
plt.title("Trade Size by Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Size USD")
plt.show()

# Trader Segmentation

# Segment 1: Frequent vs Infrequent
freq = df['Account'].value_counts()
median_freq = freq.median()

df['Trader Type'] = df['Account'].apply(
    lambda x: 'Frequent' if freq[x] > median_freq else 'Infrequent'
)

print("\nTrader Type Count")
print(df['Trader Type'].value_counts())

plt.figure(figsize=(8,5))
sns.boxplot(data=df, x='Trader Type', y='Closed PnL')
plt.title("PnL: Frequent vs Infrequent Traders")
plt.show()

#  Winners vs Inconsistent
profit = df.groupby('Account')['Closed PnL'].sum()

df['Trader Quality'] = df['Account'].apply(
    lambda x: 'Consistent Winner' if profit[x] > 0 else 'Inconsistent'
)

print("\nTrader Quality Count")
print(df['Trader Quality'].value_counts())


# Segment 3: High Risk vs Low Risk
median_size = df['Size USD'].median()

df['Risk Type'] = df['Size USD'].apply(
    lambda x: 'High Risk' if x > median_size else 'Low Risk'
)

print("\nRisk Type Count")
print(df['Risk Type'].value_counts())

# KEY INSIGHTS

print("\n")
print("KEY INSIGHTS")
print("")

print("1. Greed days generally showed stronger profitability than Fear days.")
print("2. Traders used larger trade sizes during Greed sentiment, indicating higher risk appetite.")
print("3. Frequent traders outperformed infrequent traders on cumulative PnL.")
print("4. Fear periods showed deeper average losses on losing trades.")
print("")

## PART C — ACTIONABLE OUTPUT

print("\n")
print("PART C — STRATEGY IDEAS")
print("")

print("Strategy 1: During Fear days, reduce position size and avoid overtrading.")
print("Focus only on traders with historically high win rates.")

print("\nStrategy 2: During Greed days, increase participation only for frequent")
print("and consistently profitable traders while using stop-loss discipline.")

print("\nStrategy 3 (Optional): Allocate more capital to consistent winners")
print("and reduce exposure to inconsistent traders in all market conditions.")
print("")

#  BONUS MODEL


# 1. Daily Trader Aggregation

daily = df.groupby(['Date', 'Account', 'classification']).agg({
    'Closed PnL': 'sum',
    'Size USD': 'mean',
    'Fee': 'sum',
    'Win': 'mean'
}).reset_index()

# Sort properly
daily = daily.sort_values(['Account', 'Date'])


# 2. Feature Engineering


# Previous day pnl
daily['Prev_PnL'] = daily.groupby('Account')['Closed PnL'].shift(1)

# Rolling 3-day average pnl
daily['Rolling_PnL_3'] = (
    daily.groupby('Account')['Closed PnL']
    .rolling(3, min_periods=1)
    .mean()
    .reset_index(level=0, drop=True)
)

# Next day target
daily['Next_Day_PnL'] = daily.groupby('Account')['Closed PnL'].shift(-1)

# Profitability bucket
daily['Target'] = (daily['Next_Day_PnL'] > 0).astype(int)

# Remove null rows
daily = daily.dropna()


# 3. Encode Categorical Variables
le = LabelEncoder()
daily['classification'] = le.fit_transform(daily['classification'])


# 4. Features & Target

X = daily[
    [
        'classification',
        'Closed PnL',
        'Prev_PnL',
        'Rolling_PnL_3',
        'Size USD',
        'Fee',
        'Win'
    ]
]

y = daily['Target']


# 5. Train Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# 6. Train Model

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=8,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

model.fit(X_train, y_train)


# 7. Predict

pred = model.predict(X_test)


# 8. Results

print("Accuracy:", round(accuracy_score(y_test, pred), 4))
print("\nClassification Report:\n")
print(classification_report(y_test, pred))

# 9. Confusion Matrix

cm = confusion_matrix(y_test, pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()


# 10. Feature Importance

importance = pd.Series(model.feature_importances_, index=X.columns)

plt.figure(figsize=(8,5))
importance.sort_values().plot(kind='barh')
plt.title("Feature Importance - Next Day Profitability")
plt.xlabel("Importance Score")
plt.show()

# 11. Summary

print("Model Summary:")
print("")
print("- Predicts whether trader will be profitable next day.")
print("- Uses sentiment + behavior + recent performance features.")
print("- Stronger performance indicates useful predictive signal.")
print("")

from IPython.display import Markdown, display

display(Markdown("""
## Final Conclusion

This analysis found that trader profitability and behavior vary across Fear and Greed sentiment regimes. Greed periods showed stronger profitability and larger position sizes, while Fear periods were associated with deeper losses and more defensive behavior.

Frequent and consistent traders outperformed others, suggesting trader quality and discipline matter alongside market sentiment.

A predictive model achieved **~70% accuracy**, indicating that sentiment and behavioral signals contain useful forecasting information.
"""))

